version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    # image: linuxserver/jellyfin
    container_name: jellyfin
    user: 1000:1000
    #network_mode: "host"
    ports:
      - 8096:8096
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
      - /mnt/f/TV:/hdd_tv
      - /mnt/f/TV:/hdd_movies
      - ~/.sshfs_mount/Star\ Wars:/sshfs_Star_Wars
    restart: "unless-stopped"

