version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    # image: linuxserver/jellyfin
    container_name: jellyfin
    user: 1000:1000
    group_add: 
      - "109"
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - TZ=America/Chicago
    #network_mode: "host"
    ports:
      - 8096:8096      
        #- 8920:8920 #optional
        #- 7359:7359/udp #optional
        #- 1900:1900/udp #optional
    volumes:
      - ./config:/config
      - ./cache:/cache
        #- ./jellyfin-web:/jellyfin/jellyfin-web
        #- /mnt/f/TV:/hdd_tv
      # - ${folder}/ipfs/QmRz67PcNnmyfoQ4M8nG1NdkM4WKSsFP4s4cuXt5XBgZyv:/ipfs_movies     
      # - ${folder}/ipfs/QmSmUjbeJxgtGAUyDYLa5i8QM1SRhTVgv9NPBFyREhFbnC:/ipfs_tv      
        #- /mnt/f/Movies:/hdd_movies
      - $PWD/media/movies:/local_movies
      - $PWD/media/tv:/local_tv
      - $PWD/media/yt-dl:/yt-dl
      - $PWD/xmltvdata/xmltv.xml:/xmltv.xml
      - /mnt/thx_ju/media/tv:/tv_dir:rw
      - /mnt/thx_ju/media/movies:/movies_dir:rw
      - /mnt/wd_blue_nvme/media/movies:/wd_blue_nvme_movies_dir:rw
      - /mnt/thx_ju/media/radarr-movies:/radarr-movies:rw
      - /mnt/thx_ju/media/sonarr-shows:/sonarr-shows:rw
      - /mnt/wd_blue_nvme/jellyfin_transcodes:/mnt/wd_blue_nvme/jellyfin_transcodes
      - /mnt/wd_blue_nvme/jellyfin_recordings:/mnt/wd_blue_nvme/jellyfin_recordings
    restart: "unless-stopped"
