version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    # image: linuxserver/jellyfin
    container_name: jellyfin
    # user: 1000:100
    # group_add: 
    #   - "109"
    # devices:
    #   - /dev/dri/card0:/dev/dri/card0
    #   - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - TZ=America/Chicago
    # network_mode: "host"
    # networks:
    #     - main
    ports:
      - 8096:8096      
        #- 8920:8920 #optional
        #- 7359:7359/udp #optional
        #- 1900:1900/udp #optional
    volumes:
      - ./config:/config
      - cache:/cache
      # - $PWD/media/movies:/local_movies
      # - $PWD/media/tv:/local_tv
      # - $PWD/media/yt-dl:/yt-dl
      # - $PWD/xmltvdata/xmltv.xml:/xmltv.xml
      # - /mnt/thx_ju/media/tv:/tv_dir:rw
      # - /mnt/thx_ju/media/movies:/movies_dir:rw
      # - /mnt/thx_ju/media/radarr-movies:/radarr-movies:rw
      # - /mnt/thx_ju/media/sonarr-shows:/sonarr-shows:rw
      # - /mnt/wd_blue_nvme/media/movies:/wd_blue_nvme_movies_dir:rw
      # - /mnt/wd_blue_nvme/jellyfin_transcodes:/mnt/wd_blue_nvme/jellyfin_transcodes
      # - /mnt/wd_blue_nvme/jellyfin_recordings:/mnt/wd_blue_nvme/jellyfin_recordings
      - movies:/media/movies
      - shows:/media/shows
      - youtube:/media/youtube
    restart: "unless-stopped"
volumes:
  cache: 
  # config:
  movies:
    driver_opts: 
      type: rclone 
      device: ":s3:/movies"
      o: "allow-other,uid=1000,gid=100,s3-provider=Minio,s3-access-key-id=${s3_access_key_id},s3-secret-access-key=${s3_secret_access_key},s3-endpoint=${s3_endpoint}" 
  shows:
    driver_opts: 
      type: rclone 
      device: ":s3:/shows"
      o: "allow-other,uid=1000,gid=100,s3-provider=Minio,s3-access-key-id=${s3_access_key_id},s3-secret-access-key=${s3_secret_access_key},s3-endpoint=${s3_endpoint}" 
  youtube:
    driver_opts: 
      type: rclone 
      device: ":s3:/youtube"
      o: "allow-other,uid=1000,gid=100,s3-provider=Minio,s3-access-key-id=${s3_access_key_id},s3-secret-access-key=${s3_secret_access_key},s3-endpoint=${s3_endpoint}" 
# networks:
#   main:
#     driver: bridge
#     driver_opts:
#       gateway: 192.168.2.1 # set the gateway for when multiple interfaces are used. Fixes routing when on LAN 
